# Generated by Django 4.2.19 on 2025-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('archival_period_days', models.IntegerField(default=180)),
                ('deletion_period_days', models.IntegerField(default=730)),
            ],
        ),
    ]
