# Generated by Django 4.2.19 on 2025-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_api', '0002_archivalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedstudent',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
