# Generated by Django 4.2.19 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival_api', '0003_archivedstudent_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTeacher',
            fields=[
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('archived_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
